export const BASKET_ADD_ITEM = 'BASKET/ADD_ITEM';
export const BASKET_DELETE_ITEM = 'BASKET/DELETE_ITEM';
export const BASKET_INCREASE_ITEM_AMOUNT = 'BASKET/INCREASE_ITEM_AMOUNT';
export const BASKET_DECREASE_ITEM_AMOUNT = 'BASKET/DECREASE_ITEM_AMOUNT';

export const FETCH_GOODS_REQUEST = 'FETCH_GOOODS_REQUEST';
export const FETCH_GOODS_SUCCESS = 'FETCH_GOODS_SUCCESS';
export const FETCH_GOODS_FAILURE = 'FETCH_GOODS_FAILURE';

export const ADD_NEW_GOODS_ITEM_REQUEST = 'ADD_NEW_GOODS_ITEM_REQUEST';
export const ADD_NEW_GOODS_ITEM_SUCCESS = 'ADD_NEW_GOODS_ITEM_SUCCESS';
export const ADD_NEW_GOODS_ITEM_FAILURE = 'ADD_NEW_GOODS_ITEM_FAILURE';

export const DELETE_GOODS_ITEM_REQUEST = 'DELETE_GOODS_ITEM_REQUEST';
export const DELETE_GOODS_ITEM_SUCCESS = 'DELETE_GOODS_ITEM_SUCCESS';
export const DELETE_GOODS_ITEM_FAILURE = 'DELETE_GOODS_ITEM_FAILURE';

export const UPDATE_GOODS_ITEM_REQUEST = 'UPDATE_GOODS_ITEM_REQUEST';
export const UPDATE_GOODS_ITEM_SUCCESS = 'UPDATE_GOODS_ITEM_SUCCESS';
export const UPDATE_GOODS_ITEM_FAILURE = 'UPDATE_GOODS_ITEM_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAILURE = 'FETCH_CURRENT_USER_FAILURE';

export const PROCESS_ORDER_REQUEST = 'PROCESS_ORDER_REQUEST';
export const PROCESS_ORDER_SUCCESS = 'PROCESS_ORDER_SUCCESS';
export const PROCESS_ORDER_FAILURE = 'PROCESS_ORDER_FAILURE';
